Document: calc
Title: Debian calc Manual
Author: <insert document author here>
Abstract: This manual describes what calc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/calc/calc.sgml.gz

Format: postscript
Files: /usr/share/doc/calc/calc.ps.gz

Format: text
Files: /usr/share/doc/calc/calc.text.gz

Format: HTML
Index: /usr/share/doc/calc/html/index.html
Files: /usr/share/doc/calc/html/*.html
