Document: fitutubiescalculator
Title: Debian fitutubiescalculator Manual
Author: <insert document author here>
Abstract: This manual describes what fitutubiescalculator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fitutubiescalculator/fitutubiescalculator.sgml.gz

Format: postscript
Files: /usr/share/doc/fitutubiescalculator/fitutubiescalculator.ps.gz

Format: text
Files: /usr/share/doc/fitutubiescalculator/fitutubiescalculator.text.gz

Format: HTML
Index: /usr/share/doc/fitutubiescalculator/html/index.html
Files: /usr/share/doc/fitutubiescalculator/html/*.html
